/* Generated by app/tools/render-pages.py from HTML/Markdown that exists. */
(function () {
  var L = [
  {
    "href": "index.html",
    "title": "Start",
    "module": "start",
    "folder": "",
    "section": "Start"
  },
  {
    "href": "00-MASTER-MAP/master-mindmap.html",
    "title": "Master mind map",
    "module": "map",
    "folder": "00-MASTER-MAP",
    "section": "Map"
  },
  {
    "href": "00-MASTER-MAP/hybrid-knowledge-architecture.html",
    "title": "Hybrid knowledge architecture (local / LLM / web)",
    "module": "map",
    "folder": "00-MASTER-MAP",
    "section": "Map"
  },
  {
    "href": "00-MASTER-MAP/reference-architecture.html",
    "title": "Canonical production reference architecture",
    "module": "map",
    "folder": "00-MASTER-MAP",
    "section": "Map"
  },
  {
    "href": "00-MASTER-MAP/learning-sequence.html",
    "title": "Recommended learning sequence",
    "module": "map",
    "folder": "00-MASTER-MAP",
    "section": "Map"
  },
  {
    "href": "00-MASTER-MAP/sources-and-reading.html",
    "title": "Sources and further reading",
    "module": "map",
    "folder": "00-MASTER-MAP",
    "section": "Map"
  },
  {
    "href": "why-chains.html",
    "title": "Why-chains",
    "module": "map",
    "folder": "00-MASTER-MAP",
    "section": "Map"
  },
  {
    "href": "01-FOUNDATIONS/01-overview.html",
    "title": "Foundations",
    "module": "foundations",
    "folder": "01-FOUNDATIONS",
    "section": "Foundations"
  },
  {
    "href": "01-FOUNDATIONS/02-simple.html",
    "title": "One LLM call (simple)",
    "module": "foundations",
    "folder": "01-FOUNDATIONS",
    "section": "Foundations"
  },
  {
    "href": "01-FOUNDATIONS/03-logical.html",
    "title": "Foundations (Medium)",
    "module": "foundations",
    "folder": "01-FOUNDATIONS",
    "section": "Foundations"
  },
  {
    "href": "01-FOUNDATIONS/15-real-world-example.html",
    "title": "Foundations (Complex) \u2014 how vendors document the same idea",
    "module": "foundations",
    "folder": "01-FOUNDATIONS",
    "section": "Foundations"
  },
  {
    "href": "01-FOUNDATIONS/19-comparison.html",
    "title": "When not to use an agent",
    "module": "foundations",
    "folder": "01-FOUNDATIONS",
    "section": "Foundations"
  },
  {
    "href": "01-FOUNDATIONS/16-hands-on.html",
    "title": "DO \u2014 count tokens (tiny)",
    "module": "foundations",
    "folder": "01-FOUNDATIONS",
    "section": "Foundations"
  },
  {
    "href": "02-PYTHON-FOR-AI/01-overview.html",
    "title": "Python for AI",
    "module": "foundations",
    "folder": "02-PYTHON-FOR-AI",
    "section": "Python for AI"
  },
  {
    "href": "02-PYTHON-FOR-AI/02-simple.html",
    "title": "Typed boundary (simple)",
    "module": "foundations",
    "folder": "02-PYTHON-FOR-AI",
    "section": "Python for AI"
  },
  {
    "href": "02-PYTHON-FOR-AI/19-comparison.html",
    "title": "Comparison",
    "module": "foundations",
    "folder": "02-PYTHON-FOR-AI",
    "section": "Python for AI"
  },
  {
    "href": "02-PYTHON-FOR-AI/16-hands-on.html",
    "title": "DO \u2014 fail closed on bad JSON",
    "module": "foundations",
    "folder": "02-PYTHON-FOR-AI",
    "section": "Python for AI"
  },
  {
    "href": "03-LLM-ENGINEERING/01-overview.html",
    "title": "LLM engineering",
    "module": "foundations",
    "folder": "03-LLM-ENGINEERING",
    "section": "LLM engineering"
  },
  {
    "href": "03-LLM-ENGINEERING/02-simple.html",
    "title": "Decoding and structured output (simple)",
    "module": "foundations",
    "folder": "03-LLM-ENGINEERING",
    "section": "LLM engineering"
  },
  {
    "href": "03-LLM-ENGINEERING/19-comparison.html",
    "title": "Comparison",
    "module": "foundations",
    "folder": "03-LLM-ENGINEERING",
    "section": "LLM engineering"
  },
  {
    "href": "03-LLM-ENGINEERING/16-hands-on.html",
    "title": "DO \u2014 treat the model as an untrusted serializer",
    "module": "foundations",
    "folder": "03-LLM-ENGINEERING",
    "section": "LLM engineering"
  },
  {
    "href": "04-PROMPT-ENGINEERING/01-overview.html",
    "title": "Prompt engineering",
    "module": "foundations",
    "folder": "04-PROMPT-ENGINEERING",
    "section": "Prompt engineering"
  },
  {
    "href": "04-PROMPT-ENGINEERING/02-simple.html",
    "title": "A minimum prompt spec (simple)",
    "module": "foundations",
    "folder": "04-PROMPT-ENGINEERING",
    "section": "Prompt engineering"
  },
  {
    "href": "04-PROMPT-ENGINEERING/19-comparison.html",
    "title": "Comparison (stubs, no bake-off)",
    "module": "foundations",
    "folder": "04-PROMPT-ENGINEERING",
    "section": "Prompt engineering"
  },
  {
    "href": "04-PROMPT-ENGINEERING/16-hands-on.html",
    "title": "DO \u2014 prompt as a file + fixture",
    "module": "foundations",
    "folder": "04-PROMPT-ENGINEERING",
    "section": "Prompt engineering"
  },
  {
    "href": "05-LLM-APPLICATION-ENGINEERING/01-overview.html",
    "title": "LLM applications (not agents)",
    "module": "foundations",
    "folder": "05-LLM-APPLICATION-ENGINEERING",
    "section": "LLM applications (not agents)"
  },
  {
    "href": "05-LLM-APPLICATION-ENGINEERING/02-simple.html",
    "title": "Structured classification service (simple)",
    "module": "foundations",
    "folder": "05-LLM-APPLICATION-ENGINEERING",
    "section": "LLM applications (not agents)"
  },
  {
    "href": "05-LLM-APPLICATION-ENGINEERING/19-comparison.html",
    "title": "App vs workflow vs agent",
    "module": "foundations",
    "folder": "05-LLM-APPLICATION-ENGINEERING",
    "section": "LLM applications (not agents)"
  },
  {
    "href": "05-LLM-APPLICATION-ENGINEERING/16-hands-on.html",
    "title": "DO \u2014 a six-line eval harness",
    "module": "foundations",
    "folder": "05-LLM-APPLICATION-ENGINEERING",
    "section": "LLM applications (not agents)"
  },
  {
    "href": "06-EMBEDDINGS/01-overview.html",
    "title": "Embeddings",
    "module": "rag",
    "folder": "06-EMBEDDINGS",
    "section": "Embeddings"
  },
  {
    "href": "06-EMBEDDINGS/02-simple.html",
    "title": "One encode, one compare (simple)",
    "module": "rag",
    "folder": "06-EMBEDDINGS",
    "section": "Embeddings"
  },
  {
    "href": "06-EMBEDDINGS/19-comparison.html",
    "title": "When not to embed",
    "module": "rag",
    "folder": "06-EMBEDDINGS",
    "section": "Embeddings"
  },
  {
    "href": "06-EMBEDDINGS/16-hands-on.html",
    "title": "DO \u2014 cosine on toy vectors",
    "module": "rag",
    "folder": "06-EMBEDDINGS",
    "section": "Embeddings"
  },
  {
    "href": "07-VECTOR-DATABASES/01-overview.html",
    "title": "Vector databases",
    "module": "rag",
    "folder": "07-VECTOR-DATABASES",
    "section": "Vector databases"
  },
  {
    "href": "07-VECTOR-DATABASES/02-simple.html",
    "title": "Filter then rank (simple)",
    "module": "rag",
    "folder": "07-VECTOR-DATABASES",
    "section": "Vector databases"
  },
  {
    "href": "07-VECTOR-DATABASES/19-comparison.html",
    "title": "Comparison (no winner SKU)",
    "module": "rag",
    "folder": "07-VECTOR-DATABASES",
    "section": "Vector databases"
  },
  {
    "href": "07-VECTOR-DATABASES/16-hands-on.html",
    "title": "DO \u2014 prove post-filters lie",
    "module": "rag",
    "folder": "07-VECTOR-DATABASES",
    "section": "Vector databases"
  },
  {
    "href": "08-RAG/01-overview.html",
    "title": "RAG",
    "module": "rag",
    "folder": "08-RAG",
    "section": "RAG"
  },
  {
    "href": "08-RAG/02-simple.html",
    "title": "Naive RAG (simple)",
    "module": "rag",
    "folder": "08-RAG",
    "section": "RAG"
  },
  {
    "href": "08-RAG/03-logical.html",
    "title": "RAG (Medium)",
    "module": "rag",
    "folder": "08-RAG",
    "section": "RAG"
  },
  {
    "href": "08-RAG/15-real-world-example.html",
    "title": "RAG (Complex) \u2014 official products, same pipeline",
    "module": "rag",
    "folder": "08-RAG",
    "section": "RAG"
  },
  {
    "href": "08-RAG/19-comparison.html",
    "title": "Naive vs hybrid vs permission-aware",
    "module": "rag",
    "folder": "08-RAG",
    "section": "RAG"
  },
  {
    "href": "08-RAG/16-hands-on.html",
    "title": "DO \u2014 assemble context or refuse",
    "module": "rag",
    "folder": "08-RAG",
    "section": "RAG"
  },
  {
    "href": "09-AGENTIC-RAG/01-overview.html",
    "title": "Agentic RAG",
    "module": "rag",
    "folder": "09-AGENTIC-RAG",
    "section": "Agentic RAG"
  },
  {
    "href": "09-AGENTIC-RAG/02-simple.html",
    "title": "Second retrieve, same ACL (simple)",
    "module": "rag",
    "folder": "09-AGENTIC-RAG",
    "section": "Agentic RAG"
  },
  {
    "href": "09-AGENTIC-RAG/19-comparison.html",
    "title": "When not to use agentic RAG",
    "module": "rag",
    "folder": "09-AGENTIC-RAG",
    "section": "Agentic RAG"
  },
  {
    "href": "09-AGENTIC-RAG/16-hands-on.html",
    "title": "DO \u2014 cap the loop",
    "module": "rag",
    "folder": "09-AGENTIC-RAG",
    "section": "Agentic RAG"
  },
  {
    "href": "10-AGENTS/01-overview.html",
    "title": "Agents",
    "module": "agents",
    "folder": "10-AGENTS",
    "section": "Agents"
  },
  {
    "href": "10-AGENTS/02-simple.html",
    "title": "One tool loop (simple)",
    "module": "agents",
    "folder": "10-AGENTS",
    "section": "Agents"
  },
  {
    "href": "10-AGENTS/03-logical.html",
    "title": "Agent flavors map (Medium)",
    "module": "agents",
    "folder": "10-AGENTS",
    "section": "Agents"
  },
  {
    "href": "10-AGENTS/15-real-world-example.html",
    "title": "Agents (Complex) \u2014 official runtimes, same decision",
    "module": "agents",
    "folder": "10-AGENTS",
    "section": "Agents"
  },
  {
    "href": "10-AGENTS/19-comparison.html",
    "title": "When not to use an agent",
    "module": "agents",
    "folder": "10-AGENTS",
    "section": "Agents"
  },
  {
    "href": "10-AGENTS/16-hands-on.html",
    "title": "DO \u2014 a loop with a budget",
    "module": "agents",
    "folder": "10-AGENTS",
    "section": "Agents"
  },
  {
    "href": "12-TOOLS-FUNCTION-CALLING/01-overview.html",
    "title": "Tools / function calling",
    "module": "agents",
    "folder": "12-TOOLS-FUNCTION-CALLING",
    "section": "Tools / function calling"
  },
  {
    "href": "12-TOOLS-FUNCTION-CALLING/02-simple.html",
    "title": "One tool call (sequence)",
    "module": "agents",
    "folder": "12-TOOLS-FUNCTION-CALLING",
    "section": "Tools / function calling"
  },
  {
    "href": "12-TOOLS-FUNCTION-CALLING/19-comparison.html",
    "title": "Function call vs REST vs MCP",
    "module": "agents",
    "folder": "12-TOOLS-FUNCTION-CALLING",
    "section": "Tools / function calling"
  },
  {
    "href": "12-TOOLS-FUNCTION-CALLING/16-hands-on.html",
    "title": "DO \u2014 allow-list + tenant check",
    "module": "agents",
    "folder": "12-TOOLS-FUNCTION-CALLING",
    "section": "Tools / function calling"
  },
  {
    "href": "13-MCP/01-overview.html",
    "title": "Model Context Protocol",
    "module": "agents",
    "folder": "13-MCP",
    "section": "Model Context Protocol"
  },
  {
    "href": "13-MCP/02-simple.html",
    "title": "Two servers, two clients (simple)",
    "module": "agents",
    "folder": "13-MCP",
    "section": "Model Context Protocol"
  },
  {
    "href": "13-MCP/19-comparison.html",
    "title": "MCP vs function calling vs REST",
    "module": "agents",
    "folder": "13-MCP",
    "section": "Model Context Protocol"
  },
  {
    "href": "13-MCP/16-hands-on.html",
    "title": "DO \u2014 one client per server",
    "module": "agents",
    "folder": "13-MCP",
    "section": "Model Context Protocol"
  },
  {
    "href": "11-AGENT-ORCHESTRATION/01-overview.html",
    "title": "Orchestration",
    "module": "agents",
    "folder": "11-AGENT-ORCHESTRATION",
    "section": "Orchestration"
  },
  {
    "href": "11-AGENT-ORCHESTRATION/02-simple.html",
    "title": "HITL on a write (simple)",
    "module": "agents",
    "folder": "11-AGENT-ORCHESTRATION",
    "section": "Orchestration"
  },
  {
    "href": "11-AGENT-ORCHESTRATION/19-comparison.html",
    "title": "Workflow vs graph vs free agent",
    "module": "agents",
    "folder": "11-AGENT-ORCHESTRATION",
    "section": "Orchestration"
  },
  {
    "href": "11-AGENT-ORCHESTRATION/16-hands-on.html",
    "title": "DO \u2014 a four-state machine",
    "module": "agents",
    "folder": "11-AGENT-ORCHESTRATION",
    "section": "Orchestration"
  },
  {
    "href": "14-MULTI-AGENT-SYSTEMS/01-overview.html",
    "title": "Multi-agent systems",
    "module": "agents",
    "folder": "14-MULTI-AGENT-SYSTEMS",
    "section": "Multi-agent systems"
  },
  {
    "href": "14-MULTI-AGENT-SYSTEMS/02-simple.html",
    "title": "Supervisor vs handoff (simple)",
    "module": "agents",
    "folder": "14-MULTI-AGENT-SYSTEMS",
    "section": "Multi-agent systems"
  },
  {
    "href": "14-MULTI-AGENT-SYSTEMS/19-comparison.html",
    "title": "Parallel vs hierarchy vs one agent",
    "module": "agents",
    "folder": "14-MULTI-AGENT-SYSTEMS",
    "section": "Multi-agent systems"
  },
  {
    "href": "14-MULTI-AGENT-SYSTEMS/16-hands-on.html",
    "title": "DO \u2014 a deterministic router",
    "module": "agents",
    "folder": "14-MULTI-AGENT-SYSTEMS",
    "section": "Multi-agent systems"
  },
  {
    "href": "15-NL2SQL/01-overview.html",
    "title": "NL-to-SQL",
    "module": "agents",
    "folder": "15-NL2SQL",
    "section": "NL-to-SQL"
  },
  {
    "href": "15-NL2SQL/02-simple.html",
    "title": "Parse then permit (simple)",
    "module": "agents",
    "folder": "15-NL2SQL",
    "section": "NL-to-SQL"
  },
  {
    "href": "15-NL2SQL/19-comparison.html",
    "title": "When not to generate SQL",
    "module": "agents",
    "folder": "15-NL2SQL",
    "section": "NL-to-SQL"
  },
  {
    "href": "15-NL2SQL/16-hands-on.html",
    "title": "DO \u2014 reject before execute",
    "module": "agents",
    "folder": "15-NL2SQL",
    "section": "NL-to-SQL"
  },
  {
    "href": "16-AI-DATA-ENGINEERING/01-overview.html",
    "title": "Lakehouse \u2192 index (Gate 3 light note)",
    "module": "agents",
    "folder": "16-AI-DATA-ENGINEERING",
    "section": "Lakehouse \u2192 index (Gate 3 light note)"
  },
  {
    "href": "17-LLM-DATA-PIPELINES/01-overview.html",
    "title": "Batch / CDC / stream \u2192 index (Gate 3 light note)",
    "module": "agents",
    "folder": "17-LLM-DATA-PIPELINES",
    "section": "Batch / CDC / stream \u2192 index (Gate 3 light note)"
  },
  {
    "href": "18-EVALUATION/01-overview.html",
    "title": "Evaluation",
    "module": "eval",
    "folder": "18-EVALUATION",
    "section": "Evaluation"
  },
  {
    "href": "18-EVALUATION/02-simple.html",
    "title": "Ground truth vs LLM-as-judge",
    "module": "eval",
    "folder": "18-EVALUATION",
    "section": "Evaluation"
  },
  {
    "href": "18-EVALUATION/03-logical.html",
    "title": "Harness design",
    "module": "eval",
    "folder": "18-EVALUATION",
    "section": "Evaluation"
  },
  {
    "href": "18-EVALUATION/19-comparison.html",
    "title": "When not to skip a harness",
    "module": "eval",
    "folder": "18-EVALUATION",
    "section": "Evaluation"
  },
  {
    "href": "18-EVALUATION/16-hands-on.html",
    "title": "DO \u2014 a golden-set loop (no fake score)",
    "module": "eval",
    "folder": "18-EVALUATION",
    "section": "Evaluation"
  },
  {
    "href": "18-EVALUATION/14-failure-modes.html",
    "title": "How evaluation fails",
    "module": "eval",
    "folder": "18-EVALUATION",
    "section": "Evaluation"
  },
  {
    "href": "21-AI-SECURITY/01-overview.html",
    "title": "AI security",
    "module": "security",
    "folder": "21-AI-SECURITY",
    "section": "AI security"
  },
  {
    "href": "21-AI-SECURITY/02-simple.html",
    "title": "Three OWASP doors that open together",
    "module": "security",
    "folder": "21-AI-SECURITY",
    "section": "AI security"
  },
  {
    "href": "21-AI-SECURITY/03-logical.html",
    "title": "OWASP LLM Top 10 2026 \u2192 lab controls",
    "module": "security",
    "folder": "21-AI-SECURITY",
    "section": "AI security"
  },
  {
    "href": "22-GUARDRAILS/01-overview.html",
    "title": "Guardrails",
    "module": "security",
    "folder": "22-GUARDRAILS",
    "section": "Guardrails"
  },
  {
    "href": "22-GUARDRAILS/19-comparison.html",
    "title": "When not to use the model as the filter",
    "module": "security",
    "folder": "22-GUARDRAILS",
    "section": "Guardrails"
  },
  {
    "href": "23-PHI-PII-DLP/01-overview.html",
    "title": "PII, PHI, and DLP",
    "module": "security",
    "folder": "23-PHI-PII-DLP",
    "section": "PII, PHI, and DLP"
  },
  {
    "href": "23-PHI-PII-DLP/02-simple.html",
    "title": "Layered DLP (synthetic only)",
    "module": "security",
    "folder": "23-PHI-PII-DLP",
    "section": "PII, PHI, and DLP"
  },
  {
    "href": "23-PHI-PII-DLP/19-comparison.html",
    "title": "When not to treat a classifier as DLP",
    "module": "security",
    "folder": "23-PHI-PII-DLP",
    "section": "PII, PHI, and DLP"
  },
  {
    "href": "24-AI-GOVERNANCE/01-overview.html",
    "title": "AI governance",
    "module": "security",
    "folder": "24-AI-GOVERNANCE",
    "section": "AI governance"
  },
  {
    "href": "24-AI-GOVERNANCE/03-logical.html",
    "title": "Map this lab onto NIST \u2014 not a brochure",
    "module": "security",
    "folder": "24-AI-GOVERNANCE",
    "section": "AI governance"
  },
  {
    "href": "24-AI-GOVERNANCE/19-comparison.html",
    "title": "When not to call it governance",
    "module": "security",
    "folder": "24-AI-GOVERNANCE",
    "section": "AI governance"
  },
  {
    "href": "25-RESPONSIBLE-AI/01-overview.html",
    "title": "Responsible AI",
    "module": "security",
    "folder": "25-RESPONSIBLE-AI",
    "section": "Responsible AI"
  },
  {
    "href": "25-RESPONSIBLE-AI/19-comparison.html",
    "title": "When not to collapse the three words",
    "module": "security",
    "folder": "25-RESPONSIBLE-AI",
    "section": "Responsible AI"
  },
  {
    "href": "19-OBSERVABILITY/01-overview.html",
    "title": "Observability (methods, not fake SLOs)",
    "module": "production",
    "folder": "19-OBSERVABILITY",
    "section": "Observability (methods, not fake SLOs)"
  },
  {
    "href": "20-LLMOPS/01-overview.html",
    "title": "LLMOps (release the behavior)",
    "module": "production",
    "folder": "20-LLMOPS",
    "section": "LLMOps (release the behavior)"
  },
  {
    "href": "36-AI-TESTING/01-overview.html",
    "title": "Harness vs unit tests (Gate 5 light note)",
    "module": "production",
    "folder": "36-AI-TESTING",
    "section": "Harness vs unit tests (Gate 5 light note)"
  },
  {
    "href": "37-AI-PERFORMANCE/01-overview.html",
    "title": "Performance (methods, not fake latency)",
    "module": "production",
    "folder": "37-AI-PERFORMANCE",
    "section": "Performance (methods, not fake latency)"
  },
  {
    "href": "38-AI-COST/01-overview.html",
    "title": "Cost (drivers, not invented prices)",
    "module": "production",
    "folder": "38-AI-COST",
    "section": "Cost (drivers, not invented prices)"
  },
  {
    "href": "39-AI-PRODUCTION-OPERATIONS/01-overview.html",
    "title": "Production operations (detect \u2192 fallback)",
    "module": "production",
    "folder": "39-AI-PRODUCTION-OPERATIONS",
    "section": "Production operations (detect \u2192 fallback)"
  },
  {
    "href": "26-AI-CLOUD-ARCHITECTURE/01-overview.html",
    "title": "Vendor-neutral production architecture",
    "module": "production",
    "folder": "26-AI-CLOUD-ARCHITECTURE",
    "section": "Vendor-neutral production architecture"
  },
  {
    "href": "26-AI-CLOUD-ARCHITECTURE/19-comparison.html",
    "title": "When not to start from a SKU",
    "module": "production",
    "folder": "26-AI-CLOUD-ARCHITECTURE",
    "section": "Vendor-neutral production architecture"
  },
  {
    "href": "40-REFERENCE-ARCHITECTURES/01-overview.html",
    "title": "Reference architectures A\u2013E",
    "module": "production",
    "folder": "40-REFERENCE-ARCHITECTURES",
    "section": "Reference architectures A\u2013E"
  },
  {
    "href": "40-REFERENCE-ARCHITECTURES/A-enterprise-rag.html",
    "title": "A \u2014 Enterprise RAG",
    "module": "production",
    "folder": "40-REFERENCE-ARCHITECTURES",
    "section": "Reference architectures A\u2013E"
  },
  {
    "href": "40-REFERENCE-ARCHITECTURES/B-enterprise-agent.html",
    "title": "B \u2014 Enterprise AI agent",
    "module": "production",
    "folder": "40-REFERENCE-ARCHITECTURES",
    "section": "Reference architectures A\u2013E"
  },
  {
    "href": "40-REFERENCE-ARCHITECTURES/C-nl2sql.html",
    "title": "C \u2014 Agentic NL-to-SQL",
    "module": "production",
    "folder": "40-REFERENCE-ARCHITECTURES",
    "section": "Reference architectures A\u2013E"
  },
  {
    "href": "40-REFERENCE-ARCHITECTURES/D-data-engineering-agent.html",
    "title": "D \u2014 Data engineering agent",
    "module": "production",
    "folder": "40-REFERENCE-ARCHITECTURES",
    "section": "Reference architectures A\u2013E"
  },
  {
    "href": "40-REFERENCE-ARCHITECTURES/E-multi-agent.html",
    "title": "E \u2014 Secure multi-agent platform",
    "module": "production",
    "folder": "40-REFERENCE-ARCHITECTURES",
    "section": "Reference architectures A\u2013E"
  },
  {
    "href": "27-AZURE-AI/01-overview.html",
    "title": "Azure mapping (not a stack)",
    "module": "production",
    "folder": "27-AZURE-AI",
    "section": "Azure mapping (not a stack)"
  },
  {
    "href": "28-AWS-AI/01-overview.html",
    "title": "AWS mapping (not a stack)",
    "module": "production",
    "folder": "28-AWS-AI",
    "section": "AWS mapping (not a stack)"
  },
  {
    "href": "29-GCP-AI/01-overview.html",
    "title": "GCP sketch (stub)",
    "module": "production",
    "folder": "29-GCP-AI",
    "section": "GCP sketch (stub)"
  },
  {
    "href": "30-DATABRICKS-AI/01-overview.html",
    "title": "Databricks mapping (not a stack)",
    "module": "production",
    "folder": "30-DATABRICKS-AI",
    "section": "Databricks mapping (not a stack)"
  },
  {
    "href": "41-REAL-WORLD-USE-CASES/01-overview.html",
    "title": "Fifteen use cases (not fifteen platforms)",
    "module": "labs",
    "folder": "41-REAL-WORLD-USE-CASES",
    "section": "Fifteen use cases (not fifteen platforms)"
  },
  {
    "href": "41-REAL-WORLD-USE-CASES/recent-agentic-assignments.html",
    "title": "Recent challenging agentic assignments (mid\u20132026)",
    "module": "labs",
    "folder": "41-REAL-WORLD-USE-CASES",
    "section": "Fifteen use cases (not fifteen platforms)"
  },
  {
    "href": "42-CAPSTONE-PROJECTS/01-overview.html",
    "title": "Hands-on ladder L1\u2013L10",
    "module": "labs",
    "folder": "42-CAPSTONE-PROJECTS",
    "section": "Hands-on ladder L1\u2013L10"
  },
  {
    "href": "42-CAPSTONE-PROJECTS/L01.html",
    "title": "L1 \u2014 Simple LLM application",
    "module": "labs",
    "folder": "42-CAPSTONE-PROJECTS",
    "section": "Hands-on ladder L1\u2013L10"
  },
  {
    "href": "42-CAPSTONE-PROJECTS/L02.html",
    "title": "L2 \u2014 RAG application",
    "module": "labs",
    "folder": "42-CAPSTONE-PROJECTS",
    "section": "Hands-on ladder L1\u2013L10"
  },
  {
    "href": "42-CAPSTONE-PROJECTS/L03.html",
    "title": "L3 \u2014 Production-oriented RAG",
    "module": "labs",
    "folder": "42-CAPSTONE-PROJECTS",
    "section": "Hands-on ladder L1\u2013L10"
  },
  {
    "href": "42-CAPSTONE-PROJECTS/L04.html",
    "title": "L4 \u2014 Tool-using agent",
    "module": "labs",
    "folder": "42-CAPSTONE-PROJECTS",
    "section": "Hands-on ladder L1\u2013L10"
  },
  {
    "href": "42-CAPSTONE-PROJECTS/L05.html",
    "title": "L5 \u2014 Agentic RAG",
    "module": "labs",
    "folder": "42-CAPSTONE-PROJECTS",
    "section": "Hands-on ladder L1\u2013L10"
  },
  {
    "href": "42-CAPSTONE-PROJECTS/L06.html",
    "title": "L6 \u2014 NL-to-SQL (validation first)",
    "module": "labs",
    "folder": "42-CAPSTONE-PROJECTS",
    "section": "Hands-on ladder L1\u2013L10"
  },
  {
    "href": "42-CAPSTONE-PROJECTS/L07.html",
    "title": "L7 \u2014 Multi-agent (tiny)",
    "module": "labs",
    "folder": "42-CAPSTONE-PROJECTS",
    "section": "Hands-on ladder L1\u2013L10"
  },
  {
    "href": "42-CAPSTONE-PROJECTS/L08.html",
    "title": "L8 \u2014 Secure enterprise agent",
    "module": "labs",
    "folder": "42-CAPSTONE-PROJECTS",
    "section": "Hands-on ladder L1\u2013L10"
  },
  {
    "href": "42-CAPSTONE-PROJECTS/L09.html",
    "title": "L9 \u2014 Observable production agent",
    "module": "labs",
    "folder": "42-CAPSTONE-PROJECTS",
    "section": "Hands-on ladder L1\u2013L10"
  },
  {
    "href": "42-CAPSTONE-PROJECTS/L10.html",
    "title": "L10 \u2014 Platform harness (not a platform)",
    "module": "labs",
    "folder": "42-CAPSTONE-PROJECTS",
    "section": "Hands-on ladder L1\u2013L10"
  },
  {
    "href": "43-EXPERIMENTS/01-overview.html",
    "title": "BREAK experiments",
    "module": "labs",
    "folder": "43-EXPERIMENTS",
    "section": "BREAK experiments"
  },
  {
    "href": "simulations.html",
    "title": "Simulations",
    "module": "labs",
    "folder": "",
    "section": "Simulations"
  },
  {
    "href": "48-GLOSSARY/01-overview.html",
    "title": "Lab glossary",
    "module": "reference",
    "folder": "48-GLOSSARY",
    "section": "Lab glossary"
  },
  {
    "href": "50-CHEAT-SHEETS/01-overview.html",
    "title": "High-value cheat-sheets",
    "module": "reference",
    "folder": "50-CHEAT-SHEETS",
    "section": "High-value cheat-sheets"
  },
  {
    "href": "50-CHEAT-SHEETS/rag-vs-agent.html",
    "title": "Cheat-sheet \u2014 RAG vs agent",
    "module": "reference",
    "folder": "50-CHEAT-SHEETS",
    "section": "High-value cheat-sheets"
  },
  {
    "href": "50-CHEAT-SHEETS/mcp-vs-tools.html",
    "title": "Cheat-sheet \u2014 MCP vs tools",
    "module": "reference",
    "folder": "50-CHEAT-SHEETS",
    "section": "High-value cheat-sheets"
  },
  {
    "href": "50-CHEAT-SHEETS/eval.html",
    "title": "Cheat-sheet \u2014 evaluation",
    "module": "reference",
    "folder": "50-CHEAT-SHEETS",
    "section": "High-value cheat-sheets"
  },
  {
    "href": "50-CHEAT-SHEETS/security-top10.html",
    "title": "Cheat-sheet \u2014 OWASP LLM Top 10 2026",
    "module": "reference",
    "folder": "50-CHEAT-SHEETS",
    "section": "High-value cheat-sheets"
  },
  {
    "href": "46-DESIGN-PATTERNS/01-overview.html",
    "title": "Patterns the lab already teaches",
    "module": "reference",
    "folder": "46-DESIGN-PATTERNS",
    "section": "Patterns the lab already teaches"
  },
  {
    "href": "47-ANTI-PATTERNS/01-overview.html",
    "title": "Taught anti-patterns",
    "module": "reference",
    "folder": "47-ANTI-PATTERNS",
    "section": "Taught anti-patterns"
  },
  {
    "href": "44-ARCHITECTURE-INTERVIEWS/01-overview.html",
    "title": "Architect / principal interviews",
    "module": "reference",
    "folder": "44-ARCHITECTURE-INTERVIEWS",
    "section": "Architect / principal interviews"
  }
];
  var MODULES = [
  {
    "id": "start",
    "label": "Start"
  },
  {
    "id": "map",
    "label": "Map"
  },
  {
    "id": "foundations",
    "label": "Foundations"
  },
  {
    "id": "rag",
    "label": "RAG"
  },
  {
    "id": "agents",
    "label": "Agents"
  },
  {
    "id": "eval",
    "label": "Eval"
  },
  {
    "id": "security",
    "label": "Security"
  },
  {
    "id": "production",
    "label": "Production"
  },
  {
    "id": "labs",
    "label": "Labs"
  },
  {
    "id": "reference",
    "label": "Reference"
  }
];

  function relPath() {
    var path = window.location.pathname.replace(/\\/g, "/");
    var parts = path.split("/").filter(Boolean);
    var file = parts[parts.length - 1] || "index.html";
    if (!/\.html$/i.test(file) && file.indexOf(".") === -1) file = "index.html";
    var parent = parts.length >= 2 ? parts[parts.length - 2] : "";
    if (parent === "00-MASTER-MAP") return "00-MASTER-MAP/" + file;
    if (parent === "99-META") return "99-META/" + file;
    if (/^\d{2}-/.test(parent)) return parent + "/" + file;
    return file;
  }

  function folderOf(href) {
    var i = href.lastIndexOf("/");
    return i === -1 ? "" : href.slice(0, i);
  }

  function moduleOf(href) {
    var i;
    for (i = 0; i < L.length; i++) {
      if (L[i].href === href) return L[i].module;
    }
    if (href === "simulations.html") return "labs";
    if (href === "progress.html" || href === "index.html") return "start";
    var folder = folderOf(href);
    if (!folder) return "start";
    for (i = 0; i < L.length; i++) {
      if ((L[i].folder || folderOf(L[i].href)) === folder) return L[i].module;
    }
    if (folder === "00-MASTER-MAP") return "map";
    return "start";
  }

  function indexOfHere() {
    var here = relPath();
    for (var i = 0; i < L.length; i++) {
      if (L[i].href === here) return i;
    }
    return -1;
  }

  function pageTitle() {
    var h1 = document.querySelector(".lab-article h1");
    if (h1 && h1.textContent) return h1.textContent.trim();
    return document.title.replace(/\s+—\s+AI Engineering Knowledge Lab$/, "") || relPath();
  }

  function firstInFolder(folder) {
    for (var i = 0; i < L.length; i++) {
      if ((L[i].folder || folderOf(L[i].href)) === folder) return L[i];
    }
    return null;
  }

  window.LabPath = {
    lessons: L,
    modules: MODULES,
    relPath: relPath,
    indexOfHere: indexOfHere,
    moduleOf: moduleOf,
    current: function () {
      var i = indexOfHere();
      if (i >= 0) return L[i];
      var here = relPath();
      var folder = folderOf(here);
      var first = folder ? firstInFolder(folder) : null;
      return {
        href: here,
        title: pageTitle(),
        module: (first && first.module) || moduleOf(here),
        folder: folder,
        section: first ? first.section : pageTitle()
      };
    },
    prev: function () {
      var i = indexOfHere();
      if (i > 0) return L[i - 1];
      if (i === 0) return null;
      var folder = folderOf(relPath());
      var first = folder ? firstInFolder(folder) : null;
      if (first) {
        var fi = -1;
        for (var n = 0; n < L.length; n++) {
          if (L[n].href === first.href) { fi = n; break; }
        }
        return fi > 0 ? L[fi - 1] : first;
      }
      return L[0];
    },
    next: function () {
      var i = indexOfHere();
      if (i >= 0 && i < L.length - 1) return L[i + 1];
      if (i === L.length - 1) return null;
      var folder = folderOf(relPath());
      var first = folder ? firstInFolder(folder) : null;
      if (first) {
        var fi = -1;
        for (var n = 0; n < L.length; n++) {
          if (L[n].href === first.href) { fi = n; break; }
        }
        return fi >= 0 && fi < L.length - 1 ? L[fi + 1] : L[1];
      }
      return L[1];
    },
    inModule: function (id) {
      var seen = {};
      var out = [];
      L.forEach(function (x) {
        if (x.module !== id) return;
        var key = x.folder || folderOf(x.href) || x.href;
        if (seen[key]) return;
        seen[key] = true;
        out.push({
          href: x.href,
          title: x.section || x.title,
          module: id,
          folder: key
        });
      });
      return out;
    }
  };
})();
