/* Generated by app/tools/render-pages.py — do not edit by hand. */
window.LAB_PAGE_INDEX = {
  "01-FOUNDATIONS": [
    {
      "file": "01-overview.html",
      "level": 1,
      "label": "Overview",
      "stem": "01-overview"
    },
    {
      "file": "02-simple.html",
      "level": 2,
      "label": "Simple",
      "stem": "02-simple"
    },
    {
      "file": "03-logical.html",
      "level": 3,
      "label": "Medium",
      "stem": "03-logical"
    },
    {
      "file": "15-real-world-example.html",
      "level": 6,
      "label": "Complex",
      "stem": "15-real-world-example"
    },
    {
      "file": "19-comparison.html",
      "level": 2,
      "label": "When not",
      "stem": "19-comparison"
    },
    {
      "file": "16-hands-on.html",
      "level": 4,
      "label": "Do",
      "stem": "16-hands-on"
    }
  ],
  "02-PYTHON-FOR-AI": [
    {
      "file": "01-overview.html",
      "level": 1,
      "label": "Overview",
      "stem": "01-overview"
    },
    {
      "file": "02-simple.html",
      "level": 2,
      "label": "Simple",
      "stem": "02-simple"
    },
    {
      "file": "19-comparison.html",
      "level": 2,
      "label": "When not",
      "stem": "19-comparison"
    },
    {
      "file": "16-hands-on.html",
      "level": 4,
      "label": "Do",
      "stem": "16-hands-on"
    }
  ],
  "03-LLM-ENGINEERING": [
    {
      "file": "01-overview.html",
      "level": 1,
      "label": "Overview",
      "stem": "01-overview"
    },
    {
      "file": "02-simple.html",
      "level": 2,
      "label": "Simple",
      "stem": "02-simple"
    },
    {
      "file": "19-comparison.html",
      "level": 2,
      "label": "When not",
      "stem": "19-comparison"
    },
    {
      "file": "16-hands-on.html",
      "level": 4,
      "label": "Do",
      "stem": "16-hands-on"
    }
  ],
  "04-PROMPT-ENGINEERING": [
    {
      "file": "01-overview.html",
      "level": 1,
      "label": "Overview",
      "stem": "01-overview"
    },
    {
      "file": "02-simple.html",
      "level": 2,
      "label": "Simple",
      "stem": "02-simple"
    },
    {
      "file": "19-comparison.html",
      "level": 2,
      "label": "When not",
      "stem": "19-comparison"
    },
    {
      "file": "16-hands-on.html",
      "level": 4,
      "label": "Do",
      "stem": "16-hands-on"
    }
  ],
  "05-LLM-APPLICATION-ENGINEERING": [
    {
      "file": "01-overview.html",
      "level": 1,
      "label": "Overview",
      "stem": "01-overview"
    },
    {
      "file": "02-simple.html",
      "level": 2,
      "label": "Simple",
      "stem": "02-simple"
    },
    {
      "file": "19-comparison.html",
      "level": 2,
      "label": "When not",
      "stem": "19-comparison"
    },
    {
      "file": "16-hands-on.html",
      "level": 4,
      "label": "Do",
      "stem": "16-hands-on"
    }
  ],
  "06-EMBEDDINGS": [
    {
      "file": "01-overview.html",
      "level": 1,
      "label": "Overview",
      "stem": "01-overview"
    },
    {
      "file": "02-simple.html",
      "level": 2,
      "label": "Simple",
      "stem": "02-simple"
    },
    {
      "file": "19-comparison.html",
      "level": 2,
      "label": "When not",
      "stem": "19-comparison"
    },
    {
      "file": "16-hands-on.html",
      "level": 4,
      "label": "Do",
      "stem": "16-hands-on"
    }
  ],
  "07-VECTOR-DATABASES": [
    {
      "file": "01-overview.html",
      "level": 1,
      "label": "Overview",
      "stem": "01-overview"
    },
    {
      "file": "02-simple.html",
      "level": 2,
      "label": "Simple",
      "stem": "02-simple"
    },
    {
      "file": "19-comparison.html",
      "level": 2,
      "label": "When not",
      "stem": "19-comparison"
    },
    {
      "file": "16-hands-on.html",
      "level": 4,
      "label": "Do",
      "stem": "16-hands-on"
    }
  ],
  "08-RAG": [
    {
      "file": "01-overview.html",
      "level": 1,
      "label": "Overview",
      "stem": "01-overview"
    },
    {
      "file": "02-simple.html",
      "level": 2,
      "label": "Simple",
      "stem": "02-simple"
    },
    {
      "file": "03-logical.html",
      "level": 3,
      "label": "Medium",
      "stem": "03-logical"
    },
    {
      "file": "15-real-world-example.html",
      "level": 6,
      "label": "Complex",
      "stem": "15-real-world-example"
    },
    {
      "file": "19-comparison.html",
      "level": 2,
      "label": "When not",
      "stem": "19-comparison"
    },
    {
      "file": "16-hands-on.html",
      "level": 4,
      "label": "Do",
      "stem": "16-hands-on"
    }
  ],
  "09-AGENTIC-RAG": [
    {
      "file": "01-overview.html",
      "level": 1,
      "label": "Overview",
      "stem": "01-overview"
    },
    {
      "file": "02-simple.html",
      "level": 2,
      "label": "Simple",
      "stem": "02-simple"
    },
    {
      "file": "19-comparison.html",
      "level": 2,
      "label": "When not",
      "stem": "19-comparison"
    },
    {
      "file": "16-hands-on.html",
      "level": 4,
      "label": "Do",
      "stem": "16-hands-on"
    }
  ],
  "10-AGENTS": [
    {
      "file": "01-overview.html",
      "level": 1,
      "label": "Overview",
      "stem": "01-overview"
    },
    {
      "file": "02-simple.html",
      "level": 2,
      "label": "Simple",
      "stem": "02-simple"
    },
    {
      "file": "03-logical.html",
      "level": 3,
      "label": "Medium",
      "stem": "03-logical"
    },
    {
      "file": "15-real-world-example.html",
      "level": 6,
      "label": "Complex",
      "stem": "15-real-world-example"
    },
    {
      "file": "19-comparison.html",
      "level": 2,
      "label": "When not",
      "stem": "19-comparison"
    },
    {
      "file": "16-hands-on.html",
      "level": 4,
      "label": "Do",
      "stem": "16-hands-on"
    }
  ],
  "11-AGENT-ORCHESTRATION": [
    {
      "file": "01-overview.html",
      "level": 1,
      "label": "Overview",
      "stem": "01-overview"
    },
    {
      "file": "02-simple.html",
      "level": 2,
      "label": "Simple",
      "stem": "02-simple"
    },
    {
      "file": "19-comparison.html",
      "level": 2,
      "label": "When not",
      "stem": "19-comparison"
    },
    {
      "file": "16-hands-on.html",
      "level": 4,
      "label": "Do",
      "stem": "16-hands-on"
    }
  ],
  "12-TOOLS-FUNCTION-CALLING": [
    {
      "file": "01-overview.html",
      "level": 1,
      "label": "Overview",
      "stem": "01-overview"
    },
    {
      "file": "02-simple.html",
      "level": 2,
      "label": "Simple",
      "stem": "02-simple"
    },
    {
      "file": "19-comparison.html",
      "level": 2,
      "label": "When not",
      "stem": "19-comparison"
    },
    {
      "file": "16-hands-on.html",
      "level": 4,
      "label": "Do",
      "stem": "16-hands-on"
    }
  ],
  "13-MCP": [
    {
      "file": "01-overview.html",
      "level": 1,
      "label": "Overview",
      "stem": "01-overview"
    },
    {
      "file": "02-simple.html",
      "level": 2,
      "label": "Simple",
      "stem": "02-simple"
    },
    {
      "file": "19-comparison.html",
      "level": 2,
      "label": "When not",
      "stem": "19-comparison"
    },
    {
      "file": "16-hands-on.html",
      "level": 4,
      "label": "Do",
      "stem": "16-hands-on"
    }
  ],
  "14-MULTI-AGENT-SYSTEMS": [
    {
      "file": "01-overview.html",
      "level": 1,
      "label": "Overview",
      "stem": "01-overview"
    },
    {
      "file": "02-simple.html",
      "level": 2,
      "label": "Simple",
      "stem": "02-simple"
    },
    {
      "file": "19-comparison.html",
      "level": 2,
      "label": "When not",
      "stem": "19-comparison"
    },
    {
      "file": "16-hands-on.html",
      "level": 4,
      "label": "Do",
      "stem": "16-hands-on"
    }
  ],
  "15-NL2SQL": [
    {
      "file": "01-overview.html",
      "level": 1,
      "label": "Overview",
      "stem": "01-overview"
    },
    {
      "file": "02-simple.html",
      "level": 2,
      "label": "Simple",
      "stem": "02-simple"
    },
    {
      "file": "19-comparison.html",
      "level": 2,
      "label": "When not",
      "stem": "19-comparison"
    },
    {
      "file": "16-hands-on.html",
      "level": 4,
      "label": "Do",
      "stem": "16-hands-on"
    }
  ],
  "16-AI-DATA-ENGINEERING": [
    {
      "file": "01-overview.html",
      "level": 1,
      "label": "Overview",
      "stem": "01-overview"
    }
  ],
  "17-LLM-DATA-PIPELINES": [
    {
      "file": "01-overview.html",
      "level": 1,
      "label": "Overview",
      "stem": "01-overview"
    }
  ],
  "18-EVALUATION": [
    {
      "file": "01-overview.html",
      "level": 1,
      "label": "Overview",
      "stem": "01-overview"
    },
    {
      "file": "02-simple.html",
      "level": 2,
      "label": "Simple",
      "stem": "02-simple"
    },
    {
      "file": "03-logical.html",
      "level": 3,
      "label": "Medium",
      "stem": "03-logical"
    },
    {
      "file": "19-comparison.html",
      "level": 2,
      "label": "When not",
      "stem": "19-comparison"
    },
    {
      "file": "16-hands-on.html",
      "level": 4,
      "label": "Do",
      "stem": "16-hands-on"
    },
    {
      "file": "14-failure-modes.html",
      "level": 5,
      "label": "Failures",
      "stem": "14-failure-modes"
    }
  ],
  "19-OBSERVABILITY": [
    {
      "file": "01-overview.html",
      "level": 1,
      "label": "Overview",
      "stem": "01-overview"
    }
  ],
  "20-LLMOPS": [
    {
      "file": "01-overview.html",
      "level": 1,
      "label": "Overview",
      "stem": "01-overview"
    }
  ],
  "21-AI-SECURITY": [
    {
      "file": "01-overview.html",
      "level": 1,
      "label": "Overview",
      "stem": "01-overview"
    },
    {
      "file": "02-simple.html",
      "level": 2,
      "label": "Simple",
      "stem": "02-simple"
    },
    {
      "file": "03-logical.html",
      "level": 3,
      "label": "Medium",
      "stem": "03-logical"
    }
  ],
  "22-GUARDRAILS": [
    {
      "file": "01-overview.html",
      "level": 1,
      "label": "Overview",
      "stem": "01-overview"
    },
    {
      "file": "19-comparison.html",
      "level": 2,
      "label": "When not",
      "stem": "19-comparison"
    }
  ],
  "23-PHI-PII-DLP": [
    {
      "file": "01-overview.html",
      "level": 1,
      "label": "Overview",
      "stem": "01-overview"
    },
    {
      "file": "02-simple.html",
      "level": 2,
      "label": "Simple",
      "stem": "02-simple"
    },
    {
      "file": "19-comparison.html",
      "level": 2,
      "label": "When not",
      "stem": "19-comparison"
    }
  ],
  "24-AI-GOVERNANCE": [
    {
      "file": "01-overview.html",
      "level": 1,
      "label": "Overview",
      "stem": "01-overview"
    },
    {
      "file": "03-logical.html",
      "level": 3,
      "label": "Medium",
      "stem": "03-logical"
    },
    {
      "file": "19-comparison.html",
      "level": 2,
      "label": "When not",
      "stem": "19-comparison"
    }
  ],
  "25-RESPONSIBLE-AI": [
    {
      "file": "01-overview.html",
      "level": 1,
      "label": "Overview",
      "stem": "01-overview"
    },
    {
      "file": "19-comparison.html",
      "level": 2,
      "label": "When not",
      "stem": "19-comparison"
    }
  ],
  "26-AI-CLOUD-ARCHITECTURE": [
    {
      "file": "01-overview.html",
      "level": 1,
      "label": "Overview",
      "stem": "01-overview"
    },
    {
      "file": "19-comparison.html",
      "level": 2,
      "label": "When not",
      "stem": "19-comparison"
    }
  ],
  "27-AZURE-AI": [
    {
      "file": "01-overview.html",
      "level": 1,
      "label": "Overview",
      "stem": "01-overview"
    }
  ],
  "28-AWS-AI": [
    {
      "file": "01-overview.html",
      "level": 1,
      "label": "Overview",
      "stem": "01-overview"
    }
  ],
  "29-GCP-AI": [
    {
      "file": "01-overview.html",
      "level": 1,
      "label": "Overview",
      "stem": "01-overview"
    }
  ],
  "30-DATABRICKS-AI": [
    {
      "file": "01-overview.html",
      "level": 1,
      "label": "Overview",
      "stem": "01-overview"
    }
  ],
  "36-AI-TESTING": [
    {
      "file": "01-overview.html",
      "level": 1,
      "label": "Overview",
      "stem": "01-overview"
    }
  ],
  "37-AI-PERFORMANCE": [
    {
      "file": "01-overview.html",
      "level": 1,
      "label": "Overview",
      "stem": "01-overview"
    }
  ],
  "38-AI-COST": [
    {
      "file": "01-overview.html",
      "level": 1,
      "label": "Overview",
      "stem": "01-overview"
    }
  ],
  "39-AI-PRODUCTION-OPERATIONS": [
    {
      "file": "01-overview.html",
      "level": 1,
      "label": "Overview",
      "stem": "01-overview"
    }
  ],
  "40-REFERENCE-ARCHITECTURES": [
    {
      "file": "01-overview.html",
      "level": 1,
      "label": "Overview",
      "stem": "01-overview"
    },
    {
      "file": "A-enterprise-rag.html",
      "level": 6,
      "label": "A \u2014 RAG",
      "stem": "A-enterprise-rag"
    },
    {
      "file": "B-enterprise-agent.html",
      "level": 6,
      "label": "B \u2014 Agent",
      "stem": "B-enterprise-agent"
    },
    {
      "file": "C-nl2sql.html",
      "level": 6,
      "label": "C \u2014 NL2SQL",
      "stem": "C-nl2sql"
    },
    {
      "file": "D-data-engineering-agent.html",
      "level": 6,
      "label": "D \u2014 Data agent",
      "stem": "D-data-engineering-agent"
    },
    {
      "file": "E-multi-agent.html",
      "level": 6,
      "label": "E \u2014 Multi-agent",
      "stem": "E-multi-agent"
    }
  ],
  "41-REAL-WORLD-USE-CASES": [
    {
      "file": "01-overview.html",
      "level": 1,
      "label": "Overview",
      "stem": "01-overview"
    },
    {
      "file": "recent-agentic-assignments.html",
      "level": 6,
      "label": "Recent",
      "stem": "recent-agentic-assignments"
    }
  ],
  "42-CAPSTONE-PROJECTS": [
    {
      "file": "01-overview.html",
      "level": 1,
      "label": "Overview",
      "stem": "01-overview"
    },
    {
      "file": "L01.html",
      "level": 4,
      "label": "L1",
      "stem": "L01"
    },
    {
      "file": "L02.html",
      "level": 4,
      "label": "L2",
      "stem": "L02"
    },
    {
      "file": "L03.html",
      "level": 4,
      "label": "L3",
      "stem": "L03"
    },
    {
      "file": "L04.html",
      "level": 4,
      "label": "L4",
      "stem": "L04"
    },
    {
      "file": "L05.html",
      "level": 4,
      "label": "L5",
      "stem": "L05"
    },
    {
      "file": "L06.html",
      "level": 4,
      "label": "L6",
      "stem": "L06"
    },
    {
      "file": "L07.html",
      "level": 4,
      "label": "L7",
      "stem": "L07"
    },
    {
      "file": "L08.html",
      "level": 4,
      "label": "L8",
      "stem": "L08"
    },
    {
      "file": "L09.html",
      "level": 4,
      "label": "L9",
      "stem": "L09"
    },
    {
      "file": "L10.html",
      "level": 4,
      "label": "L10",
      "stem": "L10"
    }
  ],
  "43-EXPERIMENTS": [
    {
      "file": "01-overview.html",
      "level": 1,
      "label": "Overview",
      "stem": "01-overview"
    }
  ],
  "44-ARCHITECTURE-INTERVIEWS": [
    {
      "file": "01-overview.html",
      "level": 1,
      "label": "Overview",
      "stem": "01-overview"
    }
  ],
  "46-DESIGN-PATTERNS": [
    {
      "file": "01-overview.html",
      "level": 1,
      "label": "Overview",
      "stem": "01-overview"
    }
  ],
  "47-ANTI-PATTERNS": [
    {
      "file": "01-overview.html",
      "level": 1,
      "label": "Overview",
      "stem": "01-overview"
    }
  ],
  "48-GLOSSARY": [
    {
      "file": "01-overview.html",
      "level": 1,
      "label": "Overview",
      "stem": "01-overview"
    }
  ],
  "50-CHEAT-SHEETS": [
    {
      "file": "01-overview.html",
      "level": 1,
      "label": "Overview",
      "stem": "01-overview"
    },
    {
      "file": "rag-vs-agent.html",
      "level": 2,
      "label": "RAG vs agent",
      "stem": "rag-vs-agent"
    },
    {
      "file": "mcp-vs-tools.html",
      "level": 2,
      "label": "MCP vs tools",
      "stem": "mcp-vs-tools"
    },
    {
      "file": "eval.html",
      "level": 2,
      "label": "Eval sheet",
      "stem": "eval"
    },
    {
      "file": "security-top10.html",
      "level": 2,
      "label": "OWASP map",
      "stem": "security-top10"
    }
  ]
};
