/* Generated by app/tools/render-pages.py — do not edit by hand. */
window.LAB_PAGE_INDEX = {
  "01-FOUNDATIONS": [
    {
      "file": "01-overview.html",
      "level": 1,
      "label": "Overview",
      "stem": "01-overview"
    },
    {
      "file": "02-simple.html",
      "level": 2,
      "label": "Simple",
      "stem": "02-simple"
    },
    {
      "file": "19-comparison.html",
      "level": 2,
      "label": "When not",
      "stem": "19-comparison"
    },
    {
      "file": "16-hands-on.html",
      "level": 4,
      "label": "Do",
      "stem": "16-hands-on"
    }
  ],
  "02-PYTHON-FOR-AI": [
    {
      "file": "01-overview.html",
      "level": 1,
      "label": "Overview",
      "stem": "01-overview"
    },
    {
      "file": "02-simple.html",
      "level": 2,
      "label": "Simple",
      "stem": "02-simple"
    },
    {
      "file": "19-comparison.html",
      "level": 2,
      "label": "When not",
      "stem": "19-comparison"
    },
    {
      "file": "16-hands-on.html",
      "level": 4,
      "label": "Do",
      "stem": "16-hands-on"
    }
  ],
  "03-LLM-ENGINEERING": [
    {
      "file": "01-overview.html",
      "level": 1,
      "label": "Overview",
      "stem": "01-overview"
    },
    {
      "file": "02-simple.html",
      "level": 2,
      "label": "Simple",
      "stem": "02-simple"
    },
    {
      "file": "19-comparison.html",
      "level": 2,
      "label": "When not",
      "stem": "19-comparison"
    },
    {
      "file": "16-hands-on.html",
      "level": 4,
      "label": "Do",
      "stem": "16-hands-on"
    }
  ],
  "04-PROMPT-ENGINEERING": [
    {
      "file": "01-overview.html",
      "level": 1,
      "label": "Overview",
      "stem": "01-overview"
    },
    {
      "file": "02-simple.html",
      "level": 2,
      "label": "Simple",
      "stem": "02-simple"
    },
    {
      "file": "19-comparison.html",
      "level": 2,
      "label": "When not",
      "stem": "19-comparison"
    },
    {
      "file": "16-hands-on.html",
      "level": 4,
      "label": "Do",
      "stem": "16-hands-on"
    }
  ],
  "05-LLM-APPLICATION-ENGINEERING": [
    {
      "file": "01-overview.html",
      "level": 1,
      "label": "Overview",
      "stem": "01-overview"
    },
    {
      "file": "02-simple.html",
      "level": 2,
      "label": "Simple",
      "stem": "02-simple"
    },
    {
      "file": "19-comparison.html",
      "level": 2,
      "label": "When not",
      "stem": "19-comparison"
    },
    {
      "file": "16-hands-on.html",
      "level": 4,
      "label": "Do",
      "stem": "16-hands-on"
    }
  ],
  "06-EMBEDDINGS": [
    {
      "file": "01-overview.html",
      "level": 1,
      "label": "Overview",
      "stem": "01-overview"
    },
    {
      "file": "02-simple.html",
      "level": 2,
      "label": "Simple",
      "stem": "02-simple"
    },
    {
      "file": "19-comparison.html",
      "level": 2,
      "label": "When not",
      "stem": "19-comparison"
    },
    {
      "file": "16-hands-on.html",
      "level": 4,
      "label": "Do",
      "stem": "16-hands-on"
    }
  ],
  "07-VECTOR-DATABASES": [
    {
      "file": "01-overview.html",
      "level": 1,
      "label": "Overview",
      "stem": "01-overview"
    },
    {
      "file": "02-simple.html",
      "level": 2,
      "label": "Simple",
      "stem": "02-simple"
    },
    {
      "file": "19-comparison.html",
      "level": 2,
      "label": "When not",
      "stem": "19-comparison"
    },
    {
      "file": "16-hands-on.html",
      "level": 4,
      "label": "Do",
      "stem": "16-hands-on"
    }
  ],
  "08-RAG": [
    {
      "file": "01-overview.html",
      "level": 1,
      "label": "Overview",
      "stem": "01-overview"
    },
    {
      "file": "02-simple.html",
      "level": 2,
      "label": "Simple",
      "stem": "02-simple"
    },
    {
      "file": "19-comparison.html",
      "level": 2,
      "label": "When not",
      "stem": "19-comparison"
    },
    {
      "file": "16-hands-on.html",
      "level": 4,
      "label": "Do",
      "stem": "16-hands-on"
    }
  ],
  "09-AGENTIC-RAG": [
    {
      "file": "01-overview.html",
      "level": 1,
      "label": "Overview",
      "stem": "01-overview"
    },
    {
      "file": "02-simple.html",
      "level": 2,
      "label": "Simple",
      "stem": "02-simple"
    },
    {
      "file": "19-comparison.html",
      "level": 2,
      "label": "When not",
      "stem": "19-comparison"
    },
    {
      "file": "16-hands-on.html",
      "level": 4,
      "label": "Do",
      "stem": "16-hands-on"
    }
  ],
  "10-AGENTS": [
    {
      "file": "01-overview.html",
      "level": 1,
      "label": "Overview",
      "stem": "01-overview"
    },
    {
      "file": "02-simple.html",
      "level": 2,
      "label": "Simple",
      "stem": "02-simple"
    },
    {
      "file": "19-comparison.html",
      "level": 2,
      "label": "When not",
      "stem": "19-comparison"
    },
    {
      "file": "16-hands-on.html",
      "level": 4,
      "label": "Do",
      "stem": "16-hands-on"
    },
    {
      "file": "03-logical.html",
      "level": 3,
      "label": "Logical",
      "stem": "03-logical"
    }
  ],
  "11-AGENT-ORCHESTRATION": [
    {
      "file": "01-overview.html",
      "level": 1,
      "label": "Overview",
      "stem": "01-overview"
    },
    {
      "file": "02-simple.html",
      "level": 2,
      "label": "Simple",
      "stem": "02-simple"
    },
    {
      "file": "19-comparison.html",
      "level": 2,
      "label": "When not",
      "stem": "19-comparison"
    },
    {
      "file": "16-hands-on.html",
      "level": 4,
      "label": "Do",
      "stem": "16-hands-on"
    }
  ],
  "12-TOOLS-FUNCTION-CALLING": [
    {
      "file": "01-overview.html",
      "level": 1,
      "label": "Overview",
      "stem": "01-overview"
    },
    {
      "file": "02-simple.html",
      "level": 2,
      "label": "Simple",
      "stem": "02-simple"
    },
    {
      "file": "19-comparison.html",
      "level": 2,
      "label": "When not",
      "stem": "19-comparison"
    },
    {
      "file": "16-hands-on.html",
      "level": 4,
      "label": "Do",
      "stem": "16-hands-on"
    }
  ],
  "13-MCP": [
    {
      "file": "01-overview.html",
      "level": 1,
      "label": "Overview",
      "stem": "01-overview"
    },
    {
      "file": "02-simple.html",
      "level": 2,
      "label": "Simple",
      "stem": "02-simple"
    },
    {
      "file": "19-comparison.html",
      "level": 2,
      "label": "When not",
      "stem": "19-comparison"
    },
    {
      "file": "16-hands-on.html",
      "level": 4,
      "label": "Do",
      "stem": "16-hands-on"
    }
  ],
  "14-MULTI-AGENT-SYSTEMS": [
    {
      "file": "01-overview.html",
      "level": 1,
      "label": "Overview",
      "stem": "01-overview"
    },
    {
      "file": "02-simple.html",
      "level": 2,
      "label": "Simple",
      "stem": "02-simple"
    },
    {
      "file": "19-comparison.html",
      "level": 2,
      "label": "When not",
      "stem": "19-comparison"
    },
    {
      "file": "16-hands-on.html",
      "level": 4,
      "label": "Do",
      "stem": "16-hands-on"
    }
  ],
  "15-NL2SQL": [
    {
      "file": "01-overview.html",
      "level": 1,
      "label": "Overview",
      "stem": "01-overview"
    },
    {
      "file": "02-simple.html",
      "level": 2,
      "label": "Simple",
      "stem": "02-simple"
    },
    {
      "file": "19-comparison.html",
      "level": 2,
      "label": "When not",
      "stem": "19-comparison"
    },
    {
      "file": "16-hands-on.html",
      "level": 4,
      "label": "Do",
      "stem": "16-hands-on"
    }
  ],
  "16-AI-DATA-ENGINEERING": [
    {
      "file": "01-overview.html",
      "level": 1,
      "label": "Overview",
      "stem": "01-overview"
    }
  ],
  "17-LLM-DATA-PIPELINES": [
    {
      "file": "01-overview.html",
      "level": 1,
      "label": "Overview",
      "stem": "01-overview"
    }
  ],
  "18-EVALUATION": [
    {
      "file": "01-overview.html",
      "level": 1,
      "label": "Overview",
      "stem": "01-overview"
    },
    {
      "file": "02-simple.html",
      "level": 2,
      "label": "Simple",
      "stem": "02-simple"
    },
    {
      "file": "19-comparison.html",
      "level": 2,
      "label": "When not",
      "stem": "19-comparison"
    },
    {
      "file": "16-hands-on.html",
      "level": 4,
      "label": "Do",
      "stem": "16-hands-on"
    },
    {
      "file": "03-logical.html",
      "level": 3,
      "label": "Logical",
      "stem": "03-logical"
    },
    {
      "file": "14-failure-modes.html",
      "level": 5,
      "label": "Failures",
      "stem": "14-failure-modes"
    }
  ],
  "19-OBSERVABILITY": [
    {
      "file": "01-overview.html",
      "level": 1,
      "label": "Overview",
      "stem": "01-overview"
    }
  ],
  "20-LLMOPS": [
    {
      "file": "01-overview.html",
      "level": 1,
      "label": "Overview",
      "stem": "01-overview"
    }
  ],
  "21-AI-SECURITY": [
    {
      "file": "01-overview.html",
      "level": 1,
      "label": "Overview",
      "stem": "01-overview"
    },
    {
      "file": "02-simple.html",
      "level": 2,
      "label": "Simple",
      "stem": "02-simple"
    },
    {
      "file": "03-logical.html",
      "level": 3,
      "label": "Logical",
      "stem": "03-logical"
    }
  ],
  "22-GUARDRAILS": [
    {
      "file": "01-overview.html",
      "level": 1,
      "label": "Overview",
      "stem": "01-overview"
    },
    {
      "file": "19-comparison.html",
      "level": 2,
      "label": "When not",
      "stem": "19-comparison"
    }
  ],
  "23-PHI-PII-DLP": [
    {
      "file": "01-overview.html",
      "level": 1,
      "label": "Overview",
      "stem": "01-overview"
    },
    {
      "file": "02-simple.html",
      "level": 2,
      "label": "Simple",
      "stem": "02-simple"
    },
    {
      "file": "19-comparison.html",
      "level": 2,
      "label": "When not",
      "stem": "19-comparison"
    }
  ],
  "24-AI-GOVERNANCE": [
    {
      "file": "01-overview.html",
      "level": 1,
      "label": "Overview",
      "stem": "01-overview"
    },
    {
      "file": "19-comparison.html",
      "level": 2,
      "label": "When not",
      "stem": "19-comparison"
    },
    {
      "file": "03-logical.html",
      "level": 3,
      "label": "Logical",
      "stem": "03-logical"
    }
  ],
  "25-RESPONSIBLE-AI": [
    {
      "file": "01-overview.html",
      "level": 1,
      "label": "Overview",
      "stem": "01-overview"
    },
    {
      "file": "19-comparison.html",
      "level": 2,
      "label": "When not",
      "stem": "19-comparison"
    }
  ],
  "26-AI-CLOUD-ARCHITECTURE": [
    {
      "file": "01-overview.html",
      "level": 1,
      "label": "Overview",
      "stem": "01-overview"
    },
    {
      "file": "19-comparison.html",
      "level": 2,
      "label": "When not",
      "stem": "19-comparison"
    }
  ],
  "27-AZURE-AI": [
    {
      "file": "01-overview.html",
      "level": 1,
      "label": "Overview",
      "stem": "01-overview"
    }
  ],
  "28-AWS-AI": [
    {
      "file": "01-overview.html",
      "level": 1,
      "label": "Overview",
      "stem": "01-overview"
    }
  ],
  "29-GCP-AI": [
    {
      "file": "01-overview.html",
      "level": 1,
      "label": "Overview",
      "stem": "01-overview"
    }
  ],
  "30-DATABRICKS-AI": [
    {
      "file": "01-overview.html",
      "level": 1,
      "label": "Overview",
      "stem": "01-overview"
    }
  ],
  "36-AI-TESTING": [
    {
      "file": "01-overview.html",
      "level": 1,
      "label": "Overview",
      "stem": "01-overview"
    }
  ],
  "37-AI-PERFORMANCE": [
    {
      "file": "01-overview.html",
      "level": 1,
      "label": "Overview",
      "stem": "01-overview"
    }
  ],
  "38-AI-COST": [
    {
      "file": "01-overview.html",
      "level": 1,
      "label": "Overview",
      "stem": "01-overview"
    }
  ],
  "39-AI-PRODUCTION-OPERATIONS": [
    {
      "file": "01-overview.html",
      "level": 1,
      "label": "Overview",
      "stem": "01-overview"
    }
  ],
  "40-REFERENCE-ARCHITECTURES": [
    {
      "file": "01-overview.html",
      "level": 1,
      "label": "Overview",
      "stem": "01-overview"
    }
  ],
  "41-REAL-WORLD-USE-CASES": [
    {
      "file": "01-overview.html",
      "level": 1,
      "label": "Overview",
      "stem": "01-overview"
    }
  ],
  "42-CAPSTONE-PROJECTS": [
    {
      "file": "01-overview.html",
      "level": 1,
      "label": "Overview",
      "stem": "01-overview"
    }
  ],
  "43-EXPERIMENTS": [
    {
      "file": "01-overview.html",
      "level": 1,
      "label": "Overview",
      "stem": "01-overview"
    }
  ],
  "44-ARCHITECTURE-INTERVIEWS": [
    {
      "file": "01-overview.html",
      "level": 1,
      "label": "Overview",
      "stem": "01-overview"
    }
  ],
  "46-DESIGN-PATTERNS": [
    {
      "file": "01-overview.html",
      "level": 1,
      "label": "Overview",
      "stem": "01-overview"
    }
  ],
  "47-ANTI-PATTERNS": [
    {
      "file": "01-overview.html",
      "level": 1,
      "label": "Overview",
      "stem": "01-overview"
    }
  ],
  "48-GLOSSARY": [
    {
      "file": "01-overview.html",
      "level": 1,
      "label": "Overview",
      "stem": "01-overview"
    }
  ],
  "50-CHEAT-SHEETS": [
    {
      "file": "01-overview.html",
      "level": 1,
      "label": "Overview",
      "stem": "01-overview"
    }
  ]
};
