/* Why-chains: expandable reasoning from JSON beside the page. Not a live LLM. */
(function () {
  function rootPrefix() {
    var el = document.getElementById("lab-root");
    if (!el) return "";
    var r = el.getAttribute("data-root");
    if (r === null || r === ".") return "";
    return r;
  }

  function folderAndFile() {
    var path = window.location.pathname.replace(/\\/g, "/");
    var parts = path.split("/").filter(Boolean);
    var file = parts[parts.length - 1] || "index.html";
    var parent = parts.length >= 2 ? parts[parts.length - 2] : "";
    return { parent: parent, file: file };
  }

  function render(chain) {
    var article = document.querySelector(".lab-article");
    if (!article || document.getElementById("lab-why-chain")) return;
    var box = document.createElement("aside");
    box.id = "lab-why-chain";
    box.className = "lab-why";
    var h = document.createElement("h2");
    h.textContent = "Why? " + (chain.title || "Reasoning chain");
    box.appendChild(h);
    var intro = document.createElement("p");
    intro.className = "lab-why-note";
    intro.textContent = "Stored locally. Not generated by a model in this session.";
    box.appendChild(intro);
    (chain.steps || []).forEach(function (step, i) {
      var det = document.createElement("details");
      if (i === 0) det.open = true;
      var sum = document.createElement("summary");
      sum.textContent = step.claim || ("Step " + (i + 1));
      var p = document.createElement("p");
      p.textContent = step.because || "";
      det.appendChild(sum);
      det.appendChild(p);
      box.appendChild(det);
    });
    var src = document.querySelector(".lab-article .md-source");
    if (src && src.nextSibling) article.insertBefore(box, src.nextSibling);
    else article.appendChild(box);
  }

  function boot() {
    var loc = folderAndFile();
    if (!/^\d{2}-/.test(loc.parent)) return;
    if (loc.file !== "01-overview.html") return;
    var url = rootPrefix() + loc.parent + "/why-chain.json";
    fetch(url)
      .then(function (res) {
        if (!res.ok) return null;
        return res.json();
      })
      .then(function (data) {
        if (!data || !data.steps) return;
        var applies = data.applies_to;
        if (applies && applies.length && applies.indexOf(loc.file) === -1) return;
        render(data);
      })
      .catch(function () { /* file:// or missing JSON is fine */ });
  }

  if (document.readyState === "loading") {
    document.addEventListener("DOMContentLoaded", boot);
  } else {
    boot();
  }
})();
